name: d_ball
description: Drag obstacles out of the way so the ball can reach the goal.

#publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: 1.8.0
  provider: 5.0.0
  gestures: 0.0.1
  path_provider: 2.0.2
  confetti: ^0.6.0-nullsafety
  http: 0.13.3
  audioplayers: 0.19.0
  google_mobile_ads: 0.13.0
  in_app_update: ^2.0.0
  upgrader: ^3.3.1
  video_player: 2.1.6



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - levels/
    - intro.mp3
    - alpha1.ogg
    - alpha2.ogg
    - alpha3.ogg
    - alpha4.ogg
    - alpha5.ogg
    - tick.wav
    - powerup.wav
    - dballtutorial.mp4
  # To add assets to your application, add an assets section, like this:
  fonts:
  - family: Goldman
    fonts:
    - asset: fonts/Goldman-Regular.ttf
      weight: 400
    - asset: fonts/Goldman-Bold.ttf
      weight: 700
