name: d_ball
description: Drag obstacles out of the way so the ball can reach the goal.

#publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  audioplayers: ^0.18.0 #downgrade from 0.19.0
  google_mobile_ads: ^0.12.0 #downgrade from 0.13.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.6.2
  provider: ^5.0.0
  gestures: ^0.0.1
  path_provider: ^2.0.2
  confetti: ^0.5.4+1
  firebase_admob: ^0.11.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - levels/
    - intro.mp3
    - alpha1.ogg
    - alpha2.ogg
    - alpha3.ogg
  # To add assets to your application, add an assets section, like this:
  fonts:
  - family: Goldman
    fonts:
    - asset: fonts/Goldman-Regular.ttf
      weight: 400
    - asset: fonts/Goldman-Bold.ttf
      weight: 700
